# Base configs
baseurl: ""
url: "https://spencerseale.com"
google_analytics: "UA-46465113-2"

# Flickr integration
flickr_user_id: "100488179@N04"
flickr_username: "spencerseale"

# UI configs
title: "Photography by Spencer Seale"
subtitle: ""
author: "Spencer Seale"
header:
 title: "Photography"
 subtitle: "by Spencer Seale"
footer:
 name: "Welcome, I'm Spencer."
 bio: "Currently developing bioinformatics software as a Bioinformatics Engineer, but was once also a film major. This website serves to catalog and share what is now simply a hobby. View my Flickr feed for all photos."
web_design: "AJ"

social_urls:
  linkedin: "https://www.linkedin.com/in/spencerseale"
  github: "https://github.com/spencerseale"
  flickr: "https://www.flickr.com/photos/100488179@N04/"
